Add missing Lidar parameter
PickNikRobotics/moveit_studio_kortex_ws pull request #33
Opened 2024-06-04 22:44 UTC by bgill92

Due to the LIDAR PR that went into the `ros2_mujoco` repo, a `lidar_publish_rate` `ros2_control` parameter is now required. This PR adds that PR to the Kinova URDF.

2024-06-04 23:03 UTC, adlarkin approved these changes

2024-06-04 23:40 UTC, dyackzan reviewed
Is this required for configs that don't use lidars? We probably don't want that

2024-06-04 23:43 UTC, dyackzan requested changes
I think the right fix is to make a change in the ros2_mujoco library that holds defaults for this parameter or doesn't require it unless a lidar is present in the model. I feel like this will cause confusion down the road if we require configs to set lidar params when they don't use lidars

2024-06-05 00:02 UTC, adlarkin commented
Good points, thanks @dyackzan. I did not think about the scenario where lidar isn't being used. I'm also in favor of making this default to something to handle both lidar/no lidar use cases.

2024-06-05 13:44 UTC, bgill92 commented
@adlarkin @dyackzan Made a PR for making the `lidar_publish_rate` parameter optional: https://github.com/PickNikRobotics/ros2_mujoco/pull/28

2024-06-05 23:27 UTC, dyackzan commented
Closing since https://github.com/PickNikRobotics/ros2_mujoco/pull/28 will take care of this

2024-06-05 23:27 UTC, closed without merging